name: Run e2e tests

on: [pull_request, push]

jobs:
  run-examples:
    runs-on: ubuntu-18.04
    continue-on-error: ${{ matrix.continueOnError }}

    strategy:
      matrix:
        continueOnError: [true]
        timeoutMinutes: [5]
        node: [14]

    name: E2E Test

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: microsoft/playwright-github-action@v1

      - name: restore node modules cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
  
      - run: npm install
      - run: npm run lint

      - name: Test
        run: xvfb-run --auto-servernum npm run e2e

      - name: Cleanup xvfb pidx
        uses: bcomnes/cleanup-xvfb@v1
