name: Main
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: ./
        with:
          args: npm install
      - name: Lint
        uses: ./
        with:
          args: npm run lint
      - name: Test
        uses: ./
        with:
          args: npm run e2e
